version: '3.8'

services:
  db_postgres:
    image: postgres:latest
    container_name: postgres_cont
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: image_db
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
      #DEFAULT_SERVER = '0.0.0.0'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  gradio_app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0

volumes:
  local_pgdata:
  pgadmin-data:
